# Generated by Django 5.0.2 on 2024-03-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_book_borrowed_by_book_borrowed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
