# Generated by Django 5.0.2 on 2024-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_bookstotake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstotake',
            name='location',
            field=models.CharField(choices=[('Placówka Pierwsza', 'Placówka Pierwsza, ulica Pierwsza'), ('Placówka Druga, ulica Druga', 'Placówka Druga')], max_length=200),
        ),
    ]
