# Generated by Django 5.0.2 on 2024-05-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_localopinions_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localopinions',
            unique_together=set(),
        ),
    ]
