# Generated by Django 5.0.2 on 2024-05-11 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_localopinions_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localopinions',
            unique_together={('book', 'user')},
        ),
    ]
