# Generated by Django 5.0.2 on 2024-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
