# Generated by Django 5.0.2 on 2024-03-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
