# Generated by Django 5.0.2 on 2024-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('fantasy', 'Fantasy')], max_length=20),
        ),
    ]
