# Generated by Django 5.0.2 on 2024-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_bookstotake_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstotake',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
