# Generated by Django 5.0.2 on 2024-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_bookstotake_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstotake',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
