# Generated by Django 5.0.2 on 2024-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_bookstotake_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstotake',
            name='requested_to_return',
            field=models.BooleanField(default=False),
        ),
    ]
